### PR TITLE
Refs #52 - Add contributors page

### PR DESCRIPTION
**Pull request by alessandroHenrique**
Link to task: https://github.com/fixmydjango/fixmydjango/issues/52

Menu with the Supporters' dropdown and Contributors menu item
new_menu

Supporters' dropdown menu
supporters_menu

### CODE REVIEW

**Comment by alessandroHenrique** [comment]
@andersonresende Supporters are not in the backend. Should they be? Don't think the task mentioned that.

**Comment by andersonresende** [comment]
@alessandroHenrique I am asking that because I clicked on supporters and nothing happened... :/

**Comment by alessandroHenrique** [comment]
@andersonresende Sorry for the delay. You don't need to update anything in the backend. You should be able to hover the Supporters' dropdown to see the links. Gonna take a look.

**Comment by alessandroHenrique** [comment]
@andersonresende Just to be sure, could you check if the styles of the dropdown-content class are applied?

**Comment by andersonresende** [comment]
@alessandroHenrique `dropdown-content` is not been applied. What should I do?

**Comment by andersonresende** [comment]
@alessandroHenrique worked!

**Comment by alessandroHenrique** [comment]
@andersonresende Oh, great! What was the problem?

**Comment by alessandroHenrique** [comment]
@andersonresende I could not replicate here no matter what =/

**Comment by andersonresende** [comment]
@alessandroHenrique For some reason my collectstatic didn't update my css files.

**Pull request merged**
