### PR TITLE
Refs #48 - Show "login to comment" message to non logged users

### PR DESCRIPTION
**Pull request by alessandroHenrique**
Link to task: https://github.com/fixmydjango/fixmydjango/issues/48

How to test: 
- Enter in any error page not logged and see if the message appears properly
- Click in the link, you should be redirected to the login page 

Link bellow:
login_to_comment

### CODE REVIEW

**Comment by renatooliveira** [comment]
@alessandroHenrique please fix conflicts

**Comment by alessandroHenrique** [comment]
@renatooliveira Fixed conflicts

**Comment by renatooliveira** [comment]
@alessandroHenrique after login, the user should be redirected back to the issue they were trying to comment

**Comment by alessandroHenrique** [comment]
@renatooliveira Good idea. Just did it.

**Pull request merged**
