### PR TITLE
Refs #53 - User menu is bad positioned

### PR DESCRIPTION
**Pull request by alessandroHenrique**
Link to task: https://github.com/fixmydjango/fixmydjango/issues/53

Menu before login:
before_login_menu

Menu after login:
logout

### CODE REVIEW

**Comment by alessandroHenrique** [comment]
@andersonresende Sure! gonna work on that now

**Comment by alessandroHenrique** [comment]
Hey @andersonresende could we use the Email? Because the issue said "the name of the logged user as the button name is a bit confusing"

**Comment by alessandroHenrique** [comment]
@andersonresende There are these two approaches:

Using name of the user:
navbar_with_name

Using the email:
navbar_with_email


What are your thoughts about them?

**Comment by filipeximenes** [comment]
@alessandroHenrique just put the logout button directly in the bar

**Comment by alessandroHenrique** [comment]
@filipeximenes @andersonresende 
logout

**Comment by renatooliveira** [comment]
Hey @alessandroHenrique can you fix conflicts please?

**Comment by alessandroHenrique** [comment]
@renatooliveira Done

**Pull request merged**
