### PR TITLE
Refs #35 - Track whether the error came from lib or from site

### PR DESCRIPTION
**Pull request by alessandroHenrique**
Link to task: https://github.com/fixmydjango/fixmydjango/issues/35
How to test:
- Run python manage.py migrate

- Submit a new error from your local site
- In the admin, you should see in the Error_Posts list a field called "Data came from" the value "Site"

-Submit a new error from the fixmydjango-lib
- In the admin, you should see in the Error_Posts list a field called "Data came from" the value "Lib"

### CODE REVIEW

**Comment by alessandroHenrique** [comment]
Hey @filipeximenes, what are we using it for? We should open a new issue to use this information, because it alone won't yield any value to the software.

**Comment by filipeximenes** [comment]
@alessandroHenrique for now this in only for tracking, don't worry about displaying it

**Comment by filipeximenes** [comment]
Oh, but do save the information in the database

**Comment by alessandroHenrique** [comment]
@filipeximenes Sure. Gonna create a new field to the ErrorPost model to indicate where it went from.

**Pull request merged**
